<a href="https://colab.research.google.com/github/Granero0011/DS-Unit-4-Sprint-1-NLP/blob/master/Kaggle_Competition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_20newsgroups

In [0]:
train = pd.read_csv('https://raw.githubusercontent.com/Granero0011/DS-Unit-4-Sprint-1-NLP/master/train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/Granero0011/DS-Unit-4-Sprint-1-NLP/master/test.csv')
sample_submission =pd.read_csv("https://raw.githubusercontent.com/Granero0011/DS-Unit-4-Sprint-1-NLP/master/sample_submission.csv")

In [3]:
train.head(20)

    id                author  ... pert_alcohol  category
0    1          John Hansell  ...        51.50       2.0
1    2            Dave Broom  ...        42.90       1.0
2    3          John Hansell  ...        50.00       2.0
3    4          John Hansell  ...        40.50       1.0
4    6  Davin de Kergommeaux  ...        45.00       NaN
5    9          Fred Minnick  ...        54.49       2.0
6   12          John Hansell  ...        45.00       2.0
7   14          John Hansell  ...        69.05       2.0
8   15  Davin de Kergommeaux  ...        40.00       4.0
9   16            Dave Broom  ...        47.20       NaN
10  17          John Hansell  ...        65.40       2.0
11  21          John Hansell  ...        55.70       2.0
12  22          John Hansell  ...        71.40       2.0
13  23          John Hansell  ...        53.50       2.0
14  25          John Hansell  ...        45.00       2.0
15  27          John Hansell  ...        44.80       1.0
16  28          John Hansell  ...        47.00       2.0
17  29          John Hansell  ...        63.30       2.0
18  30          John Hansell  ...        40.00       4.0
19  33          John Hansell  ...        67.40       2.0

[20 rows x 7 columns]

In [4]:
test.head(20)

      id                author  ... ratingValue  pert_alcohol
0    955          Fred Minnick  ...          90         50.00
1   3532            Lew Bryson  ...          82         49.30
2   1390  Davin de Kergommeaux  ...          89         45.00
3   1024           Gavin Smith  ...          90         55.80
4   1902           Gavin Smith  ...          87         45.90
5   1156           Gavin Smith  ...          89         46.00
6   2205            Dave Broom  ...          86         48.50
7    885            Dave Broom  ...          90         55.30
8   1116          Fred Minnick  ...          89         45.20
9   3739            Dave Broom  ...          80         54.50
10  4003          John Hansell  ...          78         45.00
11   152  Davin de Kergommeaux  ...          94         40.50
12   930            Dave Broom  ...          90         50.00
13  2840            Dave Broom  ...          84         52.90
14  2902           Gavin Smith  ...          84         40.20
15  2622          John Hansell  ...          85         43.00
16  3158            Dave Broom  ...          83         56.90
17  1290           Gavin Smith  ...          89         55.00
18  1731            Lew Bryson  ...          88         62.35
19  1537           Gavin Smith  ...          88         46.00

[20 rows x 6 columns]